server:
  port: 8080

spring:
  application:
    name: encurtador-tds
  datasource:
    url: jdbc:postgresql://localhost:5432/tds-shortener
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob.non_contextual_creation: true
    properties:
      hibernate:
        show_sql: true
