server:
  port: 8080

url_prefix: http://localhost:8080

spring:
  application:
    name: shortener-tds
  datasource:
    url: jdbc:postgresql://database:5432/shortener-tds
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
